services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    hostname: traefik
    networks:
      - private
      - public
    ports:
      - 80:80
      - 443:443
    environment:
      - HOST=$HOST
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./configs/traefik/routing:/etc/traefik/routing:ro

  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    hostname: postgres
    networks:
      - private
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: auction
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ CMD, pg_isready, -U, $POSTGRES_USER ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    hostname: redis
    networks:
      - private
    ports:
      - 6380:6379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./configs/redis.conf:/etc/redis/redis.conf:ro

  centrifugo:
    image: centrifugo/centrifugo:v5.2.2
    container_name: centrifugo
    hostname: centrifugo
    networks:
      - private
      - public
    command: centrifugo -c /etc/centrifugo/config.json
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./configs/centrifugo.json:/etc/centrifugo/config.json:ro

  minio:
    image: bitnami/minio:2024.2.4
    container_name: minio
    hostname: minio
    networks:
      - private
      - public
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_SCHEME: http
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - minio_data:/bitnami/minio/data

volumes:
  minio_data:
  postgres_data:

networks:
  public:
    driver: bridge
  private:
    driver: bridge
