services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    hostname: traefik
    networks:
      - private
      - public
    ports:
      - 80:80
      - 443:443
    environment:
      HOST: $HOST
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_data:/etc/traefik/acme
      - ./configs/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./configs/traefik/routing:/etc/traefik/routing:ro

  backend:
    build:
       context: backend
       dockerfile: Dockerfile
    image: backend  
    container_name: backend
    hostname: backend
    networks:
      - private
      - public
    ports:
      - 5000:5000
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000/
      Swagger__RoutePrefix: swagger
      Swagger__Endpoints__0__Url: https://$HOST/backend/swagger/v1/swagger.json
      Swagger__Endpoints__0__Name: swagger api
      Swagger__ServersUrls__0: https://$HOST/backend
      Minio__Endpoint: minio:9000
      Minio__AccessKey: $MINIO_ROOT_USER
      Minio__SecretKey: $MINIO_ROOT_PASSWORD
      Minio__PublicUrl: https://$HOST/static
      JsonWebToken__JsonWebKey: /etc/backend/jwk.json
      ConnectionStrings__Postgres: Server=postgres;Port=5432;Database=auction;Username=$POSTGRES_USER;Password=$POSTGRES_PASSWORD;
    volumes:
      - ./backend/jwk.json:/etc/backend/jwk.json:ro

  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    hostname: postgres
    networks:
      - private
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: auction
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ CMD, pg_isready, -U, $POSTGRES_USER ]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./configs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./configs/postgres/scripts:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    hostname: redis
    networks:
      - private
    ports:
      - 6380:6379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./configs/redis/redis.conf:/etc/redis/redis.conf:ro

  centrifugo:
    image: centrifugo/centrifugo:v5.2.2
    container_name: centrifugo
    hostname: centrifugo
    networks:
      - private
      - public
    command: centrifugo -c /etc/centrifugo/config.json
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./configs/centrifugo/centrifugo.json:/etc/centrifugo/config.json:ro

  minio:
    image: bitnami/minio:2024.2.4
    container_name: minio
    hostname: minio
    networks:
      - private
      - public
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
      MINIO_SCHEME: http
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - minio_data:/bitnami/minio/data

volumes:
  traefik_data:
  minio_data:
  postgres_data:

networks:
  public:
    driver: bridge
  private:
    driver: bridge
